apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: haproxy
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: ./haproxy
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values: {}
